export const MANUAL_DATA_SOURCE_TYPE = {
  JS_FUNCTION: 'js_function',
  CUSTOM_API: 'custom_api',
  STATIC_DATA: 'static_data',
};
export const MANUAL_DATA_SOURCE_TYPE_NAME = {
  [MANUAL_DATA_SOURCE_TYPE.JS_FUNCTION]: 'JS函数',
  [MANUAL_DATA_SOURCE_TYPE.CUSTOM_API]: '自定义API',
  [MANUAL_DATA_SOURCE_TYPE.STATIC_DATA]: '静态数据',
};

export const DATA_SOURCE_TYPE = {
  INPUT_LIKE_VIEW: 'input_like_view',
  SELECT_LIKE_VIEW: 'select_like_view',
  DATETIME_LIKE_VIEW: 'datetime_like_view',
  ...MANUAL_DATA_SOURCE_TYPE,
};

export const DATA_SOURCE_TYPE_NAME = {
  [DATA_SOURCE_TYPE.INPUT_LIKE_VIEW]: '输入框导出',
  [DATA_SOURCE_TYPE.SELECT_LIKE_VIEW]: '筛选器导出',
  [DATA_SOURCE_TYPE.DATETIME_LIKE_VIEW]: '时间导出',
  ...MANUAL_DATA_SOURCE_TYPE_NAME,
};

export const INIT_VAL_TYPE = {
  STATIC: 'static',
  FIRST: 'first',
  FIRST_N: 'first_n',
  ALL: 'all',
};

export const INIT_VAL_TYPE_NAME = {
  [INIT_VAL_TYPE.STATIC]: '使用静态值',
  [INIT_VAL_TYPE.FIRST]: '选中第一个',
  [INIT_VAL_TYPE.FIRST_N]: '选中前',
  [INIT_VAL_TYPE.ALL]: '全选',
};

export const ASYNC_STATUS = {
  PENDING: 'pending',
  FULFILLED: 'fulfilled',
  REJECTED: 'rejected',
};

export const VALUE_TYPE = {
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'boolean',
};

export const DATETIME_FORMAT = {
  UNIX_X: 'x',
  YYYY_MM_DD_HH_MM_SS_STR: 'YYYY-MM-DD HH:mm:ss',
  YYYY_MM_DD_HH_MM_STR: 'YYYY-MM-DD HH:mm',
  YYYY_MM_DD_INT: 'YYYYMMDD',
  YYYY_MM_DD_HH_INT: 'YYYYMMDDHH',
  YYYY: 'YYYY',
  YYYY_MM_STR: 'YYYY-MM',
  YYYY_MM_DD_STR: 'YYYY-MM-DD',
  YYYY_MM_DD_HH_STR: 'YYYY-MM-DD HH',
  YYYY_MM_INT: 'YYYYMM',
  YYYY_MM_DD_HH_MM_INT: 'YYYYMMDDHHmm',
  YYYY_MM_DD_HH_MM_SS_INT: 'YYYYMMDDHHmmss',
  YYYY_MM_DD_HH_MM_SS_SSS_STR: 'YYYY-MM-DD HH:mm:ss.SSS',
  YYYY_MM_DD_HH_MM_SS_SSS_INT: 'YYYYMMDDHHmmssSSS',
  UNIX_MS: 'X',
};

export const DATETIME_FORMAT_NAME = {
  [DATETIME_FORMAT.UNIX_X]: 'unix 时间戳',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_SS_STR]: 'YYYY-MM-DD HH:mm:ss',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_STR]: 'YYYY-MM-DD HH:mm',
  [DATETIME_FORMAT.YYYY_MM_DD_INT]: 'YYYYMMDD',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_INT]: 'YYYYMMDDHH',
  [DATETIME_FORMAT.YYYY]: 'YYYY',
  [DATETIME_FORMAT.YYYY_MM_STR]: 'YYYY-MM',
  [DATETIME_FORMAT.YYYY_MM_DD_STR]: 'YYYY-MM-DD',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_STR]: 'YYYY-MM-DD HH',
  [DATETIME_FORMAT.YYYY_MM_INT]: 'YYYYMM',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_INT]: 'YYYYMMDDHHmm',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_SS_INT]: 'YYYYMMDDHHmmss',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_SS_SSS_STR]: 'YYYY-MM-DD HH:mm:ss.SSS',
  [DATETIME_FORMAT.YYYY_MM_DD_HH_MM_SS_SSS_INT]: 'YYYYMMDDHHmmssSSS',
  [DATETIME_FORMAT.UNIX_MS]: 'unix时间戳(ms)',
};

